language: minimal

before_cache:
  - rm -rf ~/.cargo/registry/index/
  - rm -f  ./target/.rustc_info.json
  - find ./target/debug -maxdepth 1 -type f -delete

cache: cargo

dist: jammy

env:
  global:
    - DEBIAN_FRONTEND=noninteractive

sudo: required

jobs:
  include:
    - name: standard build
      script:
        - sudo apt-get update -y
        - sudo apt-get install -y --no-install-recommends protobuf-compiler
        - curl -sSf https://sh.rustup.rs | sh -s -- --default-toolchain none -y
        - export PATH=$HOME/.cargo/bin:$PATH
        - rustup default stable
        - cargo check

    - name: earthly build
      services:
        - docker
      script:
        - wget https://github.com/earthly/earthly/releases/download/v0.7.2/earthly-linux-amd64 -O earthly && chmod +x earthly && ./earthly bootstrap
        - ./earthly -P --ci +archive