language: minimal

cache: cargo

services:
  - docker

# jobs:
#  include:
#    - stage: earthly
#      script:
#        - wget https://github.com/earthly/earthly/releases/download/v0.6.30/earthly-linux-amd64 -O earthly && chmod +x earthly && earthly bootstrap
#        - ./earthly sat select mercury
#        - ./earthly -P --ci +archive

script:
  - apt-get update -y && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends protobuf-compiler curl ca-certificates
  - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --default-toolchain none -y
  - export PATH=$HOME/.cargo/bin:$PATH
  - rustup default stable
  - cargo check