language: minimal
services:
  - docker
script:
  - wget https://github.com/earthly/earthly/releases/download/v0.6.30/earth-linux-amd64 -O earthly && chmod +x earthly
  - ./earthly sat select mercury
  - ./earthly -P --ci +archive
