version: "0.2"

env:
  shell: bash

phases:
  build:
    commands:
      - ./scripts/ci-setup.sh
      - earthly --use-inline-cache +archive

artifacts:
  files:
    - /dist/*
  discard-paths: "yes"

cache:
  paths:
    - $HOME/.cargo/registry/**/*
