version: "0.2"

env:
  shell: bash

phases:
  build:
    commands:
      - make earthly/build

artifacts:
  files:
    - /dist/*
  discard-paths: "yes"

cache:
  paths:
    - $HOME/.cargo/registry/**/*
