version: "0.2"

env:
  shell: bash

phases:
  install:
    commands:
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2 &
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"

  build:
    commands:
      - docker run busybox nslookup google.com
      - nmcli dev show | grep 'IP4.DNS'
      - docker run --dns 8.8.8.8 busybox nslookup google.com
      - cat /etc/docker/daemon.json
      - cat /etc/resolv.conf
      - sudo ./scripts/code-build-setup.sh
      - docker run --network=host -t -v $(pwd):/workspace -v /var/run/docker.sock:/var/run/docker.sock -e NO_BUILDKIT=1 earthly/earthly:v0.6.30 --ci +archive

artifacts:
  files:
    - /dist/*
  discard-paths: "yes"

cache:
  paths:
    - $HOME/.cargo/registry/**/*
