[package]
name = "kickable"
authors = ["Hector Gray <defstream@gmail.com>"]
repository = "https://github.com/defstream/kickable-rs"
keywords = ["kick","kickable", "it", "can"]
readme = "README.md"
description = "kickable is a crate created to answer the age old question... Can I kick it?"
documentation = "https://docs.rs/kickable"
version = "0.5.21"
edition = "2021"
license = "CC0-1.0"

[features]
complete = []

[dependencies]
time = { version = ">=0.2.23"}
async-trait = "0.1.63"
async-std = { version = "1.12.0", features = ["attributes"] }
clap = { version = "4.0.32", features = ["derive"] }
exitcode = "1.1.2"
hyper = { version = ">=0.14.10", features = ["http1", "http2", "runtime", "server", "stream"] }
once_cell = "1.16.0"
rocket = "0.5.0-rc.2"
serde_json = "1.0.91"
poem = "1.3.52"
tokio = { version = "1.24.1", features = ["full"] }
tracing-subscriber = "0.3.16"
warp = "0.3.3"
gotham = "0.7.1"
serde = { version = "1.0.152", features = ["derive"] }
serde_yaml = "0.9"
rouille = "3.6.1"
graphul = "0.4.5"
trillium = "0.2.3"
trillium-router = "0.3.3"
trillium-smol = "0.2.1"
viz = "0.4.4"
log = "0.4.17"
salvo = "0.37.9"
axum = "0.6.3"
tower = { version = "0.4", features = ["util", "timeout", "load-shed", "limit"] }
tower-http = { version = "0.3.5" }
env_logger = "0.10.0"
tonic = "0.8.3"
prost = "0.11.6"
anyhow = "1.0.68"
fluent = "0.16.0"
unic-langid = { version = "0.9.1", features = ["macros"] }
rust-embed = "6.4.2"
opentelemetry = "0.18.0"
axum-tracing-opentelemetry = "0.9.0"

[dev-dependencies]
assert_cli = "0.6.3"

[build-dependencies]
tonic-build = "0.8.4"
