[package]
name = "kickable"
authors = ["Hector Gray <defstream@gmail.com>"]
repository = "https://github.com/defstream/kickable"
keywords = ["kick","kickable", "it", "can"]
readme = "README.md"
description = "kickable is a crate created to answer the age old question... Can I kick it?"
documentation = "https://docs.rs/kickable"
version = "0.2.0"
edition = "2021"
license = "MIT"

[features]
complete = []

[dependencies]
async-trait = "0.1.61"
async-std = { version = "1.12.0", features = ["attributes"] }
clap = { version = "4.0.32", features = ["derive"] }
exitcode = "1.1.2"
hyper = { version = "0.14.23", features = ["http1", "http2", "runtime", "server", "stream"] }
once_cell = "1.16.0"
rocket = "0.5.0-rc.2"
rustix = "0.36.6"
serde_json = "1.0.91"
poem = "1.3.50"
tokio = { version = "1.23.0", features = ["full"] }
tracing-subscriber = "0.3.16"
warp = "0.3.3"
gotham = "0.7.1"
serde = "1.0.152"
rouille = "3.6.1"
graphul = "0.4.5"
trillium = "0.2.3"
trillium-router = "0.3.3"
trillium-smol = "0.2.1"
viz = "0.4.4"
log = "0.4.17"
salvo = "0.37.9"
axum = "0.6.1"
tower = { version = "0.4", features = ["util", "timeout", "load-shed", "limit"] }
tower-http = { version = "0.3.5" }

[dev-dependencies]
assert_cli = "0.6.3"
