[package]
name = "kickable"
authors = ["Hector Gray <defstream@gmail.com>"]
repository = "https://github.com/defstream/kickable"
keywords = ["kick","kickable", "it", "can"]
readme = "README.md"
description = "kickable is a crate created to answer the age old question... Can I kick it?"
documentation = "https://docs.rs/kickable"
version = "0.1.5"
edition = "2021"
license = "CC0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.32", features = ["derive"] }
exitcode = "1.1.2"
once_cell = "1.16.0"
rustix = "0.36.5"
