[package]
name = "kickable"
authors = ["Hector Gray <defstream@gmail.com>"]
repository = "https://github.com/defstream/kickable"
keywords = ["kick","kickable", "it", "can"]
readme = "README.md"
description = "kickable is a crate created to answer the age old question... Can I kick it?"
documentation = "https://docs.rs/kickable"
version = "0.2.0"
edition = "2021"
license = "MIT"

[features]
complete = []

[dependencies]
async-trait = "0.1.41"
async-std = { version = "1.12.0", features = ["attributes"] }
clap = { version = "4.0.32", features = ["derive"] }
exitcode = "1.1.2"
hyper = "0.14.23"
iron = "0.6.1"
nickel = "0.11.0"
once_cell = "1.16.0"
rocket = "0.5.0-rc.2"
router = "0.6.0"
rustix = "0.36.6"
serde_json = "1.0.91"
tide = "0.16.0"
tokio = "1.23.0"

[dev-dependencies]
assert_cli = "0.6.3"
