[package]
name = "kickable"
description = "kickable is a crate created to answer the age old question... Can I kick it?"
version = "0.1.3"
edition = "2021"
license = "MIT"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
exitcode = "1.1.2"