# setup build image + dependencies
FROM joseluisq/rust-linux-darwin-builder:1.66.1 as shipyard
COPY scripts/build-setup.sh .
RUN ./build-setup.sh

# copy source code
FROM shipyard as build
WORKDIR /usr/src/kickable
COPY src src
COPY proto proto
COPY examples examples
COPY scripts scripts
COPY Cargo.lock Cargo.toml Makefile build.rs ./

# build kickable
RUN cargo build --release --all-features --locked --target aarch64-apple-darwin
