# setup build image + dependencies
FROM joseluisq/rust-linux-darwin-builder:1.66.1 as shipyard
COPY scripts/build-setup.sh .
RUN ./build-setup.sh

# copy source code
FROM shipyard as build
WORKDIR /usr/src/kickable
COPY src src
COPY proto proto
COPY examples examples
COPY scripts scripts
COPY Cargo.lock Cargo.toml Makefile build.rs ./

# build kickable
ENV RUSTFLAGS='-C linker=x86_64-linux-gnu-gcc'
RUN cargo build --release --all-features --locked --target x86_64-unknown-linux-musl