FROM defstream/builder:latest as build
WORKDIR /usr/src/kickable
COPY src src
COPY proto proto
COPY examples examples
COPY scripts scripts
COPY Cargo.lock Cargo.toml Makefile build.rs ./

# build kickable
RUN cargo build --release --all-features --locked --target aarch64-apple-darwin

LABEL description="This is the kickable container app that asks the question... Can you kick it?"
LABEL maintainer="Hector Gray <defstream@gmail.com>"
LABEL version="1.0"