jobs:
  build:
    docker:
      - image: cimg/rust:1.66.0

    parallelism: 4

    steps:
      - checkout
      - run: ./scripts/ubuntu-deps.sh
      - run: make test
      - run: make lint
      - run: make check
