version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2204:2023.10.1
    resource_class: arm.medium
    steps:
      - checkout
      - run: "sudo /bin/sh -c 'wget https://github.com/earthly/earthly/releases/download/v0.7.2/earthly-linux-arm64 -O /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly'"
      - run:
          command: FORCE_COLOR=1 earthly --ci --no-output +archive
          no_output_timeout: 2h
