version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2204:2022.04.2
    steps:
      - checkout
      - run: sudo ./scripts/ci-setup.sh
      - run: earthly sat select saturn
      - run: FORCE_COLOR=1 earthly --ci --no-output +archive
