jobs:
  build:
    docker:
      - image: cimg/rust:1.65.0

    steps:
      - checkout
      - run: cargo check --verbose --release --all-targets --all-features
      - run: cargo test --verbose --release --all-targets --all-features
      - run: cargo fmt --verbose --all -- --check
      - run: rustup component add clippy
      - run: cargo clippy -- -D warnings