jobs:
  build:
    docker:
      - image: cimg/rust:1.65.0

    parallelism: 4

    steps:
      - checkout
      - run: sudo ./scripts/ci-setup.sh
      - run: make earthly/build

  build_earthly:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      - run: sudo ./scripts/ci-setup.sh
      - run: earthly --ci +archive