version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2204:2022.04.2
    steps:
      - checkout
      - run: sudo ./scripts/ci-setup.sh
      - run: earthly sat select saturn
      - run: earthly --ci +archive --no-output

  build_normal:
    docker:
      - image: cimg/rust:1.65.0
    parallelism: 4
    steps:
      - checkout
      - run: sudo ./scripts/ci-setup.sh
      - run: make build