ARG version=0.0.0
# setup build image + dependencies
FROM kickable/builder:latest@sha256:d11ea65dfd2bea1089ee6b60e85ba8254cd7ba8b32aa0ac12fdd31f00432efe2 as build
WORKDIR /usr/src/kickable
COPY src src
COPY proto proto
COPY examples examples
COPY scripts scripts
COPY i18n i18n
COPY Cargo.lock Cargo.toml Makefile build.rs ./

# build kickable
RUN cargo build --release --all-features --locked --target aarch64-unknown-linux-musl

LABEL description="This is the kickable build image that asks the question... Can you kick it?"
LABEL maintainer="Hector Gray <hector@hectorgray.com>"
LABEL version=$version