ARG version=0.0.0
# setup build image + dependencies
FROM defstream/builder:latest as build
WORKDIR /usr/src/kickable
COPY src src
COPY proto proto
COPY examples examples
COPY scripts scripts
COPY Cargo.lock Cargo.toml Makefile build.rs ./

# build kickable
ENV RUSTFLAGS='-C linker=x86_64-linux-gnu-gcc'
RUN cargo build --release --all-features --locked --target x86_64-unknown-linux-musl

LABEL description="This is the kickable build image that asks the question... Can you kick it?"
LABEL maintainer="Hector Gray <defstream@gmail.com>"
LABEL version=$version