ARG version=0.0.0
# setup build image + dependencies
FROM kickable/builder:latest@sha256:8a9190353176a2c9838bd38b9f558d93ab5448cd4f07ac5610a43a7caa6de340 as build
WORKDIR /usr/src/kickable
COPY src src
COPY proto proto
COPY examples examples
COPY scripts scripts
COPY i18n i18n
COPY kickable.yaml Cargo.lock Cargo.toml Makefile build.rs ./

# build kickable
ENV RUSTFLAGS='-C linker=x86_64-linux-gnu-gcc'
RUN cargo build --release --all-features --locked --target x86_64-unknown-linux-musl

LABEL description="This is the kickable build image that asks the question... Can you kick it?"
LABEL maintainer="Hector Gray <hector@hectorgray.com>"
LABEL version=$version