ARG version=0.0.0
# setup build image + dependencies
FROM kickable/builder:latest@sha256:05cbf696eeba84593a2a8406e2fb49c1a431803ee9702b5f7eb743b121ad103f AS build
ARG version
WORKDIR /usr/src/kickable
COPY src src
COPY proto proto
COPY examples examples
COPY scripts scripts
COPY i18n i18n
COPY kickable.yaml Cargo.lock Cargo.toml Makefile build.rs ./

# build kickable
RUN cargo build --release --all-features --locked --target aarch64-unknown-linux-musl

LABEL description="This is the kickable build image that asks the question... Can you kick it?"
LABEL maintainer="Hector Gray <hector@hectorgray.com>"
LABEL version=$version