ARG version=0.0.0
# setup build image + dependencies
FROM kickable/builder:latest@sha256:e14f243779dbf22191a45632ff4c504673a631d670572f3412218dab8d5503a8 AS build
ARG version
WORKDIR /usr/src/kickable
COPY src src
COPY proto proto
COPY examples examples
COPY scripts scripts
COPY i18n i18n
COPY kickable.yaml Cargo.lock Cargo.toml Makefile build.rs ./

# build kickable
ENV RUSTFLAGS='-C linker=x86_64-w64-mingw32-gcc'
RUN cargo build --release --all-features --locked --target x86_64-pc-windows-gnu

LABEL description="This is the kickable build image that asks the question... Can you kick it?"
LABEL maintainer="Hector Gray <hector@hectorgray.com>"
LABEL version=$version