ARG version=0.0.0
# setup build image + dependencies
FROM kickable/builder:latest@sha256:7b6d9592303d8e2961e958cdb105329738b5612a6972681c87622f04935831ba as build
WORKDIR /usr/src/kickable
COPY src src
COPY proto proto
COPY examples examples
COPY scripts scripts
COPY i18n i18n
COPY Cargo.lock Cargo.toml Makefile build.rs ./

# build kickable
ENV RUSTFLAGS='-C linker=x86_64-w64-mingw32-gcc'
RUN cargo build --release --all-features --locked --target x86_64-pc-windows-gnu

LABEL description="This is the kickable build image that asks the question... Can you kick it?"
LABEL maintainer="Hector Gray <hector@hectorgray.com>"
LABEL version=$version