on:
  push:
    branches:
      - main

name: depot

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: harden runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.depot.dev:443
            auth.docker.io:443
            dl.depot.dev:443
            github.com:443
            index.docker.io:443
            objects.githubusercontent.com:443
            registry-1.docker.io:443
            undefined:443

      - name: checkout
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5

      - name: setup depot
        uses: depot/setup-action@eb2efd6287c794d456be5e1a7963fa8772c39ce5 # v1.5.0

      - name: docker login
        run: docker login --username kickable  --password "${{ secrets.DOCKER_HUB }}"

      - run: depot build --platform linux/amd64,linux/arm64 -f docker/Dockerfile.builder -t kickable/builder -q --load .
        env:
          DEPOT_TOKEN: ${{ secrets.DEPOT_TOKEN }}


