on:
  push:
    branches:
      - main

name: depot

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: harden runner
        uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09 # v2.5.1
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.depot.dev:443
            auth.docker.io:443
            dl.depot.dev:443
            github.com:443
            index.docker.io:443
            objects.githubusercontent.com:443
            registry-1.docker.io:443
            undefined:443

      - name: checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0

      - name: setup depot
        uses: depot/setup-action@0cd1716c2eb8606eee7f18de8f87fddd0e1c2fd2 # v1.4.2

      - name: docker login
        run: docker login --username kickable  --password "${{ secrets.DOCKER_HUB }}"

      - run: depot build --platform linux/amd64,linux/arm64 -f docker/Dockerfile.builder -t kickable/builder .
        env:
          DEPOT_TOKEN: ${{ secrets.DEPOT_TOKEN }}


