on:
  push:
    branches-ignore:
      - 'v*'
  pull_request:

name: depot

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: depot/setup-action@v1
      - uses: depot/build-push-action@v1
        with:
          project: mA50ur1KuM
          context: .
          file: ./docker/Dockerfile
          push: false
          token: ${{ secrets.DEPOT_TOKEN }}