on:
  push:
    branches:
      - main
  pull_request:

name: depot

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: depot/setup-action@v1
      - name: docker login
        run: docker login --username kickable  --password "${{ secrets.DOCKER_HUB }}"
      - uses: depot/setup-action@v1
      - run: depot build --platform linux/amd64,linux/arm64 -f docker/Dockerfile.cross .
        env:
          DEPOT_TOKEN: ${{ secrets.DEPOT_TOKEN }}
