on:
  push:
    branches-ignore:
      - 'v*'
  pull_request:
    branches: [ "main" ]

name: earthly

permissions:
  contents: read

jobs:
  build:
    name: kickable - earthly build
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
      EARTHLY_TOKEN: ${{ secrets.EARTHLY_TOKEN }}
    steps:
      - name: harden runner
        uses: step-security/harden-runner@03bee3930647ebbf994244c21ddbc0d4933aab4f # v2.3.0
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: checkout
        uses: actions/checkout@83b7061638ee4956cf7545a6f7efe594e5ad0247 # v3.5.1

      - name: update git branch
        run: |
          branch=""
          if [ -n "$GITHUB_HEAD_REF" ]; then
            branch="$GITHUB_HEAD_REF"
          else
            branch="${GITHUB_REF##*/}"
          fi
          git checkout -b "$branch" || true

      - name: setup earthly
        uses: earthly/actions-setup@cce953f2ea75f5ff76f6483a788bac66a733de3a # v1.0.5
        with:
          version: latest

      - name: earthly cache
        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
        continue-on-error: false
        with:
          path: |
            /var/lib/docker/volumes/earthly-cache/
          key: earthly-${{ hashFiles('**/*') }}
          restore-keys: earthly-

      - name: run build
        run: earthly --ci +archive