on:
  push:
    branches-ignore:
      - 'v*'
  pull_request:
    branches-ignore:
      - "dependabot/**"
      - "renovate/**"

name: earthly

permissions:
  contents: read

jobs:
  build:
    name: kickable - earthly build
    runs-on: ubuntu-latest
    if: github.repository == 'defstream/kickable-rs'
    env:
      FORCE_COLOR: 1
      EARTHLY_TOKEN: ${{ secrets.EARTHLY_TOKEN }}
    steps:
      - name: harden runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit

      - name: checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

      - name: update git branch
        run: |
          branch=""
          if [ -n "$GITHUB_HEAD_REF" ]; then
            branch="$GITHUB_HEAD_REF"
          else
            branch="${GITHUB_REF##*/}"
          fi
          git checkout -b "$branch" || true

      - name: setup earthly
        uses: earthly/actions-setup@f2bef5b3261c9d75ac09a578552257195fea300a # v1.0.9
        with:
          version: latest

      - name: select satellite
        run: earthly sat select maui

      - name: hash
        id: hash
        shell: bash
        run: |
          echo ::set-output name=cargo_lock::${{ hashFiles('Cargo.lock') }}
          echo ::set-output name=workflow_yml::${{ hashFiles('.github/workflows/earthly.yml') }}

      - name: cache earthly
        uses: actions/cache@13aacd865c20de90d75de3b17ebe84f7a17d57d2 # v4.0.0
        continue-on-error: false
        with:
          path: /var/lib/docker/volumes/earthly-cache/
          key: earthly-${{ steps.hash.outputs.cargo_lock }}-${{ steps.hash.outputs.workflow_yml }}

      - name: run build
        run: earthly --ci --save-inline-cache --use-inline-cache --max-remote-cache +archive