on:
  push:
    branches-ignore:
      - 'v*'
  pull_request:
    branches: [ "main" ]

name: earthly

permissions:
  contents: read

jobs:
  build:
    name: kickable - earthly build
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
      EARTHLY_TOKEN: ${{ secrets.EARTHLY_TOKEN }}
    steps:
      - name: harden runner
        uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09 # v2.5.1
        with:
          egress-policy: audit

      - name: checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: update git branch
        run: |
          branch=""
          if [ -n "$GITHUB_HEAD_REF" ]; then
            branch="$GITHUB_HEAD_REF"
          else
            branch="${GITHUB_REF##*/}"
          fi
          git checkout -b "$branch" || true

      - name: setup earthly
        uses: earthly/actions-setup@135d686cdc4619918fd1b542d0a08d61dd104518 # v1.0.7
        with:
          version: latest

      - name: select satellite
        run: earthly sat select europa

      - name: hash
        id: hash
        shell: bash
        run: |
          echo ::set-output name=cargo_lock::${{ hashFiles('Cargo.lock') }}
          echo ::set-output name=workflow_yml::${{ hashFiles('.github/workflows/earthly.yml') }}

      - name: cache earthly
        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
        continue-on-error: false
        with:
          path: /var/lib/docker/volumes/earthly-cache/
          key: earthly-${{ steps.hash.outputs.cargo_lock }}-${{ steps.hash.outputs.workflow_yml }}

      - name: run build
        run: earthly --ci +archive