# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler

name: label
on: [pull_request_target]

permissions:
  contents: read

jobs:
  label:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
    - name: harden runner
      uses: step-security/harden-runner@128a63446a954579617e875aaab7d2978154e969 # v2.4.0
      with:
        egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

    - name: label
      uses: actions/labeler@ba790c862c380240c6d5e7427be5ace9a05c754b # v4.0.3
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
