on:
  push:
    branches:
      - main

name: main

jobs:
  build:
    name: kickable - std build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        toolchain:
          - stable
        target:
          - x86_64-pc-windows-gnu
          - aarch64-unknown-linux-gnu
          - x86_64-unknown-linux-gnu

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: install stable
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.toolchain }}
          target:  ${{ matrix.target }}
          override: true

      - name: install rust
        run: rustup update ${{ matrix.rust }} && rustup target add ${{ matrix.target }}

      - name: install cross-compilation tools
        uses: taiki-e/setup-cross-toolchain-action@v1
        with:
          target: ${{ matrix.target }}

      - name: install dependencies
        run: |
          sudo apt update 
          sudo apt install protobuf-compiler -y -o Acquire::Retries=5

      - name: build
        uses: actions-rs/cargo@v1
        with:
          use-cross: false
          command: check
          args: --verbose --release --all-targets --all-features --target ${{ matrix.target }}

  test:
    name: kickable - test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: install dependencies
        run: |
          sudo apt update 
          sudo apt install protobuf-compiler -y -o Acquire::Retries=5

      - name: test
        uses: actions-rs/cargo@v1
        with:
          command: test

  lint:
    name: kickable - lint
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install stable
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: install dependencies
        run: |
          sudo apt update 
          sudo apt install protobuf-compiler -y -o Acquire::Retries=5

      - name: cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

  coverage:
    name: kickable - coverage
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install dependencies
        run: |
          sudo apt update 
          sudo apt install protobuf-compiler -y -o Acquire::Retries=5

      - name: cargo install tarpaulin
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-tarpaulin

      - name: cargo tarpaulin
        uses: actions-rs/tarpaulin@v0.1
        with:
          version: '0.25.0'
          args: '--out Xml --out Lcov --all-features -- --test-threads 1'

      - name: archive code coverage results
        uses: actions/upload-artifact@v1
        with:
          name: code-coverage-report
          path: cobertura.xml

      - name: upload to Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: './lcov.info'

  audit:
    name: kickable - audit
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: audit
        uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: OSSF Scorecard action
        uses: ossf/scorecard-action@v2.1.2
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true

      # Upload the results to GitHub's code scanning dashboard.
      - name: "Upload to code-scanning"
        uses: github/codeql-action/upload-sarif@5f532563584d71fdef14ee64d17bafb34f751ce5 # tag=v1.0.26
        with:
          sarif_file: results.sarif

