on:
  push:
    branches:
      - main

name: main

jobs:
  build:
    name: kickable - build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        toolchain:
          - stable
        target:
          - x86_64-pc-windows-gnu
          - aarch64-unknown-linux-gnu
          - x86_64-unknown-linux-gnu

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: install stable
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.toolchain }}
          target:  ${{ matrix.target }}
          override: true

      - name: install rust
        run: rustup update ${{ matrix.rust }} && rustup target add ${{ matrix.target }}

      - name: install cross-compilation tools
        uses: taiki-e/setup-cross-toolchain-action@v1
        with:
          target: ${{ matrix.target }}

      - name: install dependencies
        run: |
          sudo apt update 
          sudo apt install protobuf-compiler -y -o Acquire::Retries=5

      - name: build
        uses: actions-rs/cargo@v1
        with:
          use-cross: false
          command: check
          args: --verbose --release --all-targets --all-features --target ${{ matrix.target }}

  test:
    name: kickable - test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: install dependencies
        run: |
          sudo apt update 
          sudo apt install protobuf-compiler -y -o Acquire::Retries=5

      - name: test
        uses: actions-rs/cargo@v1
        with:
          command: test

  lint:
    name: kickable - lint
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install stable
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: install dependencies
        run: |
          sudo apt update 
          sudo apt install protobuf-compiler -y -o Acquire::Retries=5

      - name: cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

      - name: cargo install tarpaulin
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-tarpaulin

      - name: cargo tarpaulin
        uses: actions-rs/cargo@v1
        with:
          command: tarpaulin
          args: --ciserver github --coveralls ${{ secrets.COVERALLS }}

  audit:
    name: kickable - audit
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: audit
        uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
