name: Cargo Build & Test

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: kickable - build, lint and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v3
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }} && rustup component add clippy
      - run: cargo build --verbose --release --all-features --examples --tests
      - uses: actions-rs/clippy-check@v1
        with:
         token: ${{ secrets.GITHUB_TOKEN }}
         args: --all-features
      - run: cargo test --verbose --release --all-features --examples --tests