on: [push, pull_request]

name: kickable

jobs:
  build:
    name: kickable - build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
        include:
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
          - target: aarch64-apple-darwin
            os: macos-latest
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: x86_64-apple-darwin
            os: macos-latest
          - target: universal-apple-darwin
            os: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: install stable
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.toolchain }}
          target:  ${{ matrix.target }}
          override: true

      - name: Install Rust
        run: rustup update ${{ matrix.rust }} && rustup target add ${{ matrix.target }}

      - name: install cross-compilation tools
        uses: taiki-e/setup-cross-toolchain-action@v1
        with:
          target: ${{ matrix.target }}

      - name: install protobuf library
        run: sudo apt install protobuf-compiler -y

      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          # (required) Comma-separated list of binary names (non-extension portion of filename) to build and upload.
          # Note that glob pattern is not supported yet.
          bin: kickable
          # (optional) Target triple, default is host triple.
          target: ${{ matrix.target }}
          # (required) GitHub token for uploading assets to GitHub Releases.
          token: ${{ secrets.GITHUB_TOKEN }}
          features: all
          include: README.md CHANGELOG.md


  test:
    name: kickable - test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          
      - name: install protoc
        uses: arduino/setup-protoc@v1

      - name: test
        uses: actions-rs/cargo@v1
        with:
          command: test

  lint:
    name: kickable - lint
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install stable
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy
          
      - name: install protoc
        uses: arduino/setup-protoc@v1

      - name: cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

      - name: tarpaulin
        uses: actions-rs/tarpaulin@v0.1
        with:
          version: '0.22.0'
          args: --ciserver github --coveralls ${{ secrets.COVERALLS }} -- --test-threads 1

  audit:
    name: kickable - audit
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: audit
        uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
