on:
  push:
    tags:
      - 'v*'

name: ghcr.io release

permissions:
  contents: read

jobs:
  build:
    name: kickable - ghcr.io release
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
      EARTHLY_TOKEN: ${{ secrets.EARTHLY_TOKEN }}
    permissions:
      packages: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit

      - name: checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: update git branch
        run: |
          branch=""
          if [ -n "$GITHUB_HEAD_REF" ]; then
            branch="$GITHUB_HEAD_REF"
          else
            branch="${GITHUB_REF##*/}"
          fi
          git checkout -b "$branch" || true

      - name: setup qemu
        uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 # v3.0.0
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - name: setup earthly
        uses: earthly/actions-setup@6e152169bdc2c3c53fe75d763863d260ac9b1f82 # v1.0.12
        with:
          version: "latest"

      - name: select satellite
        run: earthly sat select manoa

      - name: docker login
        run: docker login ghcr.io --username ${{ github.repository_owner }}  --password "${{ secrets.GITHUB_TOKEN }}"

      - name: set version
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: build and push docker app
        run: |
          echo ${{ github.repository }}
          earthly --ci --push --save-inline-cache --use-inline-cache --max-remote-cache +kickable --use-inline-cache --save-inline-cache --max-remote-cache --VERSION="$VERSION" --REPOSITORY="ghcr.io/defstream/kickable-rs"

      - name: build docker services
        run: |
          earthly --ci --push --save-inline-cache --use-inline-cache --max-remote-cache +services --use-inline-cache --save-inline-cache --max-remote-cache --VERSION="$VERSION" --REPOSITORY="ghcr.io/defstream/kickable-rs"
          
