on:
  push:
    tags:
      - 'v*'

name: dockerhub release

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
      EARTHLY_TOKEN: ${{ secrets.EARTHLY_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - name: update git branch
        run: |
          branch=""
          if [ -n "$GITHUB_HEAD_REF" ]; then
            branch="$GITHUB_HEAD_REF"
          else
            branch="${GITHUB_REF##*/}"
          fi
          git checkout -b "$branch" || true

      - name: setup ci
        run: sudo ./scripts/ci-setup.sh

      - name: select satellite
        run: earthly sat select venus

      - name: docker login
        run: docker login --username kickable  --password "${{ secrets.DOCKER_HUB }}"

      - name: build and push dockerhub app
        run: earthly --push +kickable --version="${{ github.ref_name }}"

      - name: build dockerhub services
        run: |
          earthly --push +axum --version="${{ github.ref_name }}" 
          earthly --push +gotham --version="${{ github.ref_name }}"
          earthly --push +graphul --version="${{ github.ref_name }}"
          earthly --push +poem --version="${{ github.ref_name }}"
          earthly --push +rocket --version="${{ github.ref_name }}"
          earthly --push +rouille --version="${{ github.ref_name }}"
          earthly --push +salvo --version="${{ github.ref_name }}"
          earthly --push +tonic-client --version="${{ github.ref_name }}"
          earthly --push +tonic-server --version="${{ github.ref_name }}"
          earthly --push +trillium --version="${{ github.ref_name }}"
          earthly --push +viz --version="${{ github.ref_name }}"
          earthly --push +warp --version="${{ github.ref_name }}"