on:
  push:
    tags:
      - 'v*'

name: release

jobs:
  create:
    name: create
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: release_notes
        run: |
          if test -f ".changes/${{ github.ref_name }}.md"; then
             echo "NOTES=$(cat .changes/${{ github.ref_name }}.md)" >> $GITHUB_OUTPUT
          fi

      - id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body:   ${{ steps.release_notes.outputs.NOTES }}
          draft: false
          prerelease: false

  build:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    needs: create
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            archive: zip
          - target: x86_64-unknown-linux-musl
            archive: tar.gz
          - target: x86_64-apple-darwin
            archive: zip
    steps:
      - name: checkout
        uses: actions/checkout@v2
        
      - name: compile ${{ matrix.target }}
        id: compile
        uses: rust-build/rust-build.action@v1.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          RUSTTARGET: ${{ matrix.target }}
          ARCHIVE_TYPES: ${{ matrix.archive }}
          EXTRA_FILES: README.md CHANGELOG.md LICENSE
          PRE_BUILD: "scripts/alpine-setup.sh"
          UPLOAD_MODE: none

      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Binary
          path: |
            ${{ steps.compile.outputs.BUILT_ARCHIVE }}
            ${{ steps.compile.outputs.BUILT_CHECKSUM }}

      - name: upload-asset
        id: upload-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{needs.create.outputs.upload_url}}
          asset_path:  ${{ steps.compile.outputs.BUILT_ARCHIVE }}
          asset_name: kickable-rs_${{ github.ref_name }}_${{ matrix.target }}.${{ matrix.archive }}
          asset_content_type: application/zip

      - name: upload-sha
        id: upload-sha
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{needs.create.outputs.upload_url}}
          asset_path:  ${{ steps.compile.outputs.BUILT_CHECKSUM }}
          asset_name: kickable-rs_${{ github.ref_name }}_${{ matrix.target }}.${{ matrix.archive }}.sha256
          asset_content_type: application/text