on:
  push:
    tags:
      - 'v*'

name: dockerhub builder release

jobs:
  build:
    name: kickable - dockerhub builder release
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
      EARTHLY_TOKEN: ${{ secrets.EARTHLY_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - name: update git branch
        run: |
          branch=""
          if [ -n "$GITHUB_HEAD_REF" ]; then
            branch="$GITHUB_HEAD_REF"
          else
            branch="${GITHUB_REF##*/}"
          fi
          git checkout -b "$branch" || true

      - name: setup qemu
        uses: docker/setup-qemu-action@v2
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - name: setup ci
        run: sudo ./scripts/ci-setup.sh

      - name: select satellite
        run: earthly sat select venus

      - name: docker login
        run: docker login --username kickable  --password "${{ secrets.DOCKER_HUB }}"

      - name: set version
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - uses: depot/setup-action@v1
        with:
          version: 1.3.0

      - uses: depot/build-push-action@v1
        with:
          project: mA50ur1KuM
          context: .
          file: ./docker/Dockerfile.builder
          platforms: linux/amd64,linux/arm64
          push: true
          token: ${{ secrets.DEPOT_TOKEN }}
          tags: kickable/builder:latest
