on:
  push:
    tags:
      - 'v*'

name: dockerhub builder release

permissions:
  contents: read

jobs:
  build:
    name: kickable - dockerhub builder release
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
      EARTHLY_TOKEN: ${{ secrets.EARTHLY_TOKEN }}
    steps:
      - name: harden runner
        uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09 # v2.5.1
        with:
          egress-policy: audit

      - name: checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0

      - name: update git branch
        run: |
          branch=""
          if [ -n "$GITHUB_HEAD_REF" ]; then
            branch="$GITHUB_HEAD_REF"
          else
            branch="${GITHUB_REF##*/}"
          fi
          git checkout -b "$branch" || true

      - name: setup qemu
        uses: docker/setup-qemu-action@2b82ce82d56a2a04d2637cd93a637ae1b359c0a7 # v2.2.0
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - name: docker login
        run: docker login --username kickable  --password "${{ secrets.DOCKER_HUB }}"

      - name: set version
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - uses: depot/setup-action@0cd1716c2eb8606eee7f18de8f87fddd0e1c2fd2 # v1.4.2
        with:
          version: 2.7.6

      - uses: depot/build-push-action@39acb3f766a908058e746f5c7a166f73e4cdcb17 # v1.8.1
        with:
          project: mA50ur1KuM
          context: .
          file: ./docker/Dockerfile.builder
          platforms: linux/amd64,linux/arm64
          push: true
          token: ${{ secrets.DEPOT_TOKEN }}
          tags: kickable/builder:latest
