on:
  push:
    tags:
      - 'v*'

name: release

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
      EARTHLY_TOKEN: ${{ secrets.EARTHLY_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - name: update git branch
        run: |
          branch=""
          if [ -n "$GITHUB_HEAD_REF" ]; then
            branch="$GITHUB_HEAD_REF"
          else
            branch="${GITHUB_REF##*/}"
          fi
          git checkout -b "$branch" || true

      - name: setup ci
      - run: sudo ./scripts/ci-setup.sh

      - name: select satellite
        run: earthly sat select neptune

      - name: run build
        run: earthly +archive --version='${{ github.ref_name }}'

      - name: create release notes
        run: |
          if test -f ".changes/${{ github.ref_name }}.md"; then
             echo "NOTES=$(cat .changes/${{ github.ref_name }}.md)" >> $GITHUB_OUTPUT
          fi

      - id: create
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body:   ${{ steps.release_notes.outputs.NOTES }}
          draft: false
          prerelease: false

      - name: upload-aarch64-unknown-linux-musl
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{needs.create.outputs.upload_url}}
          asset_path:  dist/kickable-rs_v${{ github.ref_name }}_aarch64-unknown-linux-musl.tar.gz
          asset_content_type: application/tar+gzip

      - name: upload-aarch64-unknown-linux-musl-sha256
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{needs.create.outputs.upload_url}}
          asset_path:  dist/kickable-rs_v${{ github.ref_name }}_aarch64-unknown-linux-musl.tar.gz.sha256
          asset_content_type: application/text

      - name: upload-x86_64-unknown-linux-musl
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{needs.create.outputs.upload_url}}
          asset_path:  dist/kickable-rs_v${{ github.ref_name }}_x86_64-unknown-linux-musl.tar.gz
          asset_content_type: application/tar+gzip

      - name: upload-x86_64-unknown-linux-musl-sha256
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{needs.create.outputs.upload_url}}
          asset_path:  dist/kickable-rs_v${{ github.ref_name }}_x86_64-unknown-linux-musl.tar.gz.sha256
          asset_content_type: application/text

      - name: upload-aarch64-apple-darwin
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{needs.create.outputs.upload_url}}
          asset_path:  dist/kickable-rs_v${{ github.ref_name }}_aarch64-apple-darwin.zip
          asset_content_type: application/zip

      - name: upload-aarch64-apple-darwin-sha256
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{needs.create.outputs.upload_url}}
          asset_path:  dist/kickable-rs_v${{ github.ref_name }}_aarch64-apple-darwin.zip.sha256
          asset_content_type: application/text

      - name: upload-x86_64-apple-darwin
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{needs.create.outputs.upload_url}}
          asset_path:  dist/kickable-rs_v${{ github.ref_name }}_x86_64-apple-darwin.zip
          asset_content_type: application/zip

      - name: upload-x86_64-apple-darwin-sha256
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{needs.create.outputs.upload_url}}
          asset_path:  dist/kickable-rs_v${{ github.ref_name }}_x86_64-apple-darwin.zip.sha256
          asset_content_type: application/text

      - name: upload-x86_64-pc-windows-gnu
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{needs.create.outputs.upload_url}}
          asset_path:  dist/kickable-rs_v${{ github.ref_name }}_x86_64-pc-windows-gnu.zip
          asset_content_type: application/zip

      - name: upload-x86_64-pc-windows-gnu-sha256
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{needs.create.outputs.upload_url}}
          asset_path:  dist/kickable-rs_v${{ github.ref_name }}_x86_64-pc-windows-gnu.zip.sha256
          asset_content_type: application/text
