on:
  push:
    tags:
      - 'v*'

name: release

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: write  # for softprops/action-gh-release to create GitHub release
    name: kickable - release
    runs-on: ubuntu-latest
    env:

      FORCE_COLOR: 1
      EARTHLY_TOKEN: ${{ secrets.EARTHLY_TOKEN }}
    steps:
      - name: harden runner
        uses: step-security/harden-runner@55d479fb1c5bcad5a4f9099a5d9f37c8857b2845 # v2.4.1
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: checkout
        uses: actions/checkout@83b7061638ee4956cf7545a6f7efe594e5ad0247 # v3.5.1

      - name: update git branch
        run: |
          branch=""
          if [ -n "$GITHUB_HEAD_REF" ]; then
            branch="$GITHUB_HEAD_REF"
          else
            branch="${GITHUB_REF##*/}"
          fi
          git checkout -b "$branch" || true

      - name: setup earthly
        uses: earthly/actions-setup@135d686cdc4619918fd1b542d0a08d61dd104518 # v1.0.7
        with:
          version: "latest"

      - name: run build and archive
        run: earthly --ci --output +archive --VERSION="${{ github.ref_name }}"

      - name: create
        id: create
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v1
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: false
          generate_release_notes: true
          files: |
            dist/kickable-rs_${{ github.ref_name }}_aarch64-apple-darwin.zip
            dist/kickable-rs_${{ github.ref_name }}_aarch64-apple-darwin.zip.sha256
            dist/kickable-rs_${{ github.ref_name }}_aarch64-unknown-linux-musl.tar.gz
            dist/kickable-rs_${{ github.ref_name }}_aarch64-unknown-linux-musl.tar.gz.sha256
            dist/kickable-rs_${{ github.ref_name }}_x86_64-apple-darwin.zip
            dist/kickable-rs_${{ github.ref_name }}_x86_64-apple-darwin.zip.sha256
            dist/kickable-rs_${{ github.ref_name }}_x86_64-pc-windows-gnu.zip
            dist/kickable-rs_${{ github.ref_name }}_x86_64-pc-windows-gnu.zip.sha256
            dist/kickable-rs_${{ github.ref_name }}_x86_64-unknown-linux-musl.tar.gz
            dist/kickable-rs_${{ github.ref_name }}_x86_64-unknown-linux-musl.tar.gz.sha256
