on:
  push:
    tags:
      - 'v*'

name: dockerhub builder release

jobs:
  build:
    name: kickable - dockerhub builder release
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
      EARTHLY_TOKEN: ${{ secrets.EARTHLY_TOKEN }}
    steps:
      - name: harden runner
        uses: step-security/harden-runner@03bee3930647ebbf994244c21ddbc0d4933aab4f # v2.3.0
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: checkout
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0

      - name: update git branch
        run: |
          branch=""
          if [ -n "$GITHUB_HEAD_REF" ]; then
            branch="$GITHUB_HEAD_REF"
          else
            branch="${GITHUB_REF##*/}"
          fi
          git checkout -b "$branch" || true

      - name: setup qemu
        uses: docker/setup-qemu-action@e81a89b1732b9c48d79cd809d8d81d79c4647a18 # v2.1.0
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - name: docker login
        run: docker login --username kickable  --password "${{ secrets.DOCKER_HUB }}"

      - name: set version
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - uses: depot/setup-action@ad05a752b7f61b7a0b2d19d8b02b4da9d9c761a3 # v1.3.0
        with:
          version: 1.6.0

      - uses: depot/build-push-action@62042fcd4e8fb573d56567ca1b1f75a404557ba4 # v1.4.0
        with:
          project: mA50ur1KuM
          context: .
          file: ./docker/Dockerfile.builder
          platforms: linux/amd64,linux/arm64
          push: true
          token: ${{ secrets.DEPOT_TOKEN }}
          tags: kickable/builder:latest
