on:
  push:
    tags:
      - 'v*'

name: dockerhub release

permissions:
  contents: read

jobs:
  build:
    name: kickable - dockerhub release
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
      EARTHLY_TOKEN: ${{ secrets.EARTHLY_TOKEN }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@1f99358870fe1c846a3ccba386cc2b2246836776 # v2.2.1
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: checkout
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0

      - name: update git branch
        run: |
          branch=""
          if [ -n "$GITHUB_HEAD_REF" ]; then
            branch="$GITHUB_HEAD_REF"
          else
            branch="${GITHUB_REF##*/}"
          fi
          git checkout -b "$branch" || true

      - name: setup qemu
        uses: docker/setup-qemu-action@e81a89b1732b9c48d79cd809d8d81d79c4647a18 # v2.1.0
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - name: setup earthly
        uses: earthly/actions-setup@cce953f2ea75f5ff76f6483a788bac66a733de3a # v1.0.5
        with:
          version: "latest"

      - name: docker login
        run: docker login --username kickable  --password "${{ secrets.DOCKER_HUB }}"

      - name: set version
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: build and push dockerhub app
        run: earthly --ci --output --push +kickable --VERSION="$VERSION" --REPOSITORY="kickable"

      - name: build dockerhub services
        run: |
          earthly --ci --output --push +services --VERSION="$VERSION" --REPOSITORY="kickable"