on:
  push:
    tags:
      - 'v*'

name: release

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
      EARTHLY_TOKEN: ${{ secrets.EARTHLY_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - name: update git branch
        run: |
          branch=""
          if [ -n "$GITHUB_HEAD_REF" ]; then
            branch="$GITHUB_HEAD_REF"
          else
            branch="${GITHUB_REF##*/}"
          fi
          git checkout -b "$branch" || true

      - name: setup ci
        run: sudo ./scripts/ci-setup.sh

      - name: select satellite
        run: earthly sat select neptune

      - name: docker login
        run: docker login --username kickable  --password "${{ secrets.DOCKER_HUB }}"

      - name: run build
        run: earthly +archive --version="${{ github.ref_name }}"

      - name: build and push dockerhub app
        run: earthly --push +kickable --version="${{ github.ref_name }}" 

      - name: build dockerhub services
        run: |
          earthly --push +axum --version="${{ github.ref_name }}" 
          earthly --push +gotham --version="${{ github.ref_name }}"
          earthly --push +graphul --version="${{ github.ref_name }}"
          earthly --push +poem --version="${{ github.ref_name }}"
          earthly --push +rocket --version="${{ github.ref_name }}"
          earthly --push +rouille --version="${{ github.ref_name }}"
          earthly --push +salvo --version="${{ github.ref_name }}"
          earthly --push +tonic-client --version="${{ github.ref_name }}"
          earthly --push +tonic-server --version="${{ github.ref_name }}"
          earthly --push +trillium --version="${{ github.ref_name }}"
          earthly --push +viz --version="${{ github.ref_name }}"
          earthly --push +warp --version="${{ github.ref_name }}"


      - name: build and push docker app
        run: |
          docker login ghcr.io --username ${{ github.repository_owner }}  --password "${{ secrets.GITHUB_TOKEN }}"
          earthly --push +kickable --version="${{ github.ref_name }}" --repository="${{ github.repository }}"

      - name: build docker services
        run: |
          docker login ghcr.io --username ${{ github.repository_owner }}  --password "${{ secrets.GITHUB_TOKEN }}" 
          earthly --push +axum --version="${{ github.ref_name }}" --repository="${{ github.repository }}"
          earthly --push +gotham --version="${{ github.ref_name }}" --repository="${{ github.repository }}"
          earthly --push +graphul --version="${{ github.ref_name }}" --repository="${{ github.repository }}"
          earthly --push +poem --version="${{ github.ref_name }}" --repository="${{ github.repository }}"
          earthly --push +rocket --version="${{ github.ref_name }}" --repository="${{ github.repository }}"
          earthly --push +rouille --version="${{ github.ref_name }}" --repository="${{ github.repository }}"
          earthly --push +salvo --version="${{ github.ref_name }}" --repository="${{ github.repository }}"
          earthly --push +tonic-client --version="${{ github.ref_name }}" --repository="${{ github.repository }}"
          earthly --push +tonic-server --version="${{ github.ref_name }}" --repository="${{ github.repository }}"
          earthly --push +trillium --version="${{ github.ref_name }}" --repository="${{ github.repository }}"
          earthly --push +viz --version="${{ github.ref_name }}" --repository="${{ github.repository }}"
          earthly --push +warp --version="${{ github.ref_name }}" --repository="${{ github.repository }}"

      - name: create
        id: create
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: false
          generate_release_notes: true
          files: |
            dist/kickable-rs_${{ github.ref_name }}_aarch64-apple-darwin.zip
            dist/kickable-rs_${{ github.ref_name }}_aarch64-apple-darwin.zip.sha256
            dist/kickable-rs_${{ github.ref_name }}_aarch64-unknown-linux-musl.tar.gz
            dist/kickable-rs_${{ github.ref_name }}_aarch64-unknown-linux-musl.tar.gz.sha256
            dist/kickable-rs_${{ github.ref_name }}_x86_64-apple-darwin.zip
            dist/kickable-rs_${{ github.ref_name }}_x86_64-apple-darwin.zip.sha256
            dist/kickable-rs_${{ github.ref_name }}_x86_64-pc-windows-gnu.zip
            dist/kickable-rs_${{ github.ref_name }}_x86_64-pc-windows-gnu.zip.sha256
            dist/kickable-rs_${{ github.ref_name }}_x86_64-unknown-linux-musl.tar.gz
            dist/kickable-rs_${{ github.ref_name }}_x86_64-unknown-linux-musl.tar.gz.sha256
