on:
  push:
    tags:
      - 'v*'

name: ghcr.io release

permissions:
  contents: read

jobs:
  build:
    name: kickable - ghcr.io release
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
      EARTHLY_TOKEN: ${{ secrets.EARTHLY_TOKEN }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09 # v2.5.1
        with:
          egress-policy: audit

      - name: checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0

      - name: update git branch
        run: |
          branch=""
          if [ -n "$GITHUB_HEAD_REF" ]; then
            branch="$GITHUB_HEAD_REF"
          else
            branch="${GITHUB_REF##*/}"
          fi
          git checkout -b "$branch" || true

      - name: setup qemu
        uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 # v3.0.0
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - name: setup earthly
        uses: earthly/actions-setup@be3fe0c1f84e9776b5a184d21bf7a4a779ea2e6b # v1.0.8
        with:
          version: "latest"

      - name: select satellite
        run: earthly sat select maui

      - name: docker login
        run: docker login ghcr.io --username ${{ github.repository_owner }}  --password "${{ secrets.GITHUB_TOKEN }}"

      - name: build and push docker app
        run: |
          echo ${{ github.repository }}
          earthly --ci --output --push +kickable --VERSION="${GITHUB_REF_NAME#v}" --REPOSITORY="ghcr.io/defstream/kickable-rs"

      - name: build docker services
        run: |
          earthly --ci --output --push +services --VERSION="${GITHUB_REF_NAME#v}" --REPOSITORY="ghcr.io/defstream/kickable-rs"
          
