on:
  push:
    tags:
      - 'v*'

name: ghcr.io release

jobs:
  build:
    name: kickable - ghcr.io release
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
      EARTHLY_TOKEN: ${{ secrets.EARTHLY_TOKEN }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@1f99358870fe1c846a3ccba386cc2b2246836776 # v2.2.1
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0

      - name: update git branch
        run: |
          branch=""
          if [ -n "$GITHUB_HEAD_REF" ]; then
            branch="$GITHUB_HEAD_REF"
          else
            branch="${GITHUB_REF##*/}"
          fi
          git checkout -b "$branch" || true

      - name: setup qemu
        uses: docker/setup-qemu-action@e81a89b1732b9c48d79cd809d8d81d79c4647a18 # v2.1.0

      - name: setup earthly
        uses: earthly/actions-setup@v1
        with:
          version: "latest"

      - name: select satellite
        run: earthly sat select mars

      - name: docker login
        run: docker login ghcr.io --username ${{ github.repository_owner }}  --password "${{ secrets.GITHUB_TOKEN }}"

      - name: set version
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: build and push docker app
        run: |
          earthly --ci --output --push +kickable --VERSION="$VERSION" --REPOSITORY="ghcr.io/${{ github.repository }}"

      - name: build docker services
        run: |
          earthly --ci --output --push +services --VERSION="$VERSION" --REPOSITORY="ghcr.io/${{ github.repository }}"