on:
  release:
    types: [created]

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: "validate changelog"
        uses: brettcannon/check-for-changed-files@v1.1.0
        with:
          file-pattern: |
            .changes/unreleased/*.yaml
            CHANGELOG.md
          skip-label: "skip changelog"
          failure-message: "Missing a changelog file in ${file-pattern}; please add one or apply the ${skip-label} label to the pull request"
  upload-assets:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: kickable
          tar: unix
          zip: windows
          token: ${{ secrets.GITHUB_TOKEN }}
          include: CHANGELOG.md README.md LICENSE
