on:
  push:
    branches:
      - artifactory
    tags:
      - 'v*'

name: artifactory release

jobs:
  build:
    name: kickable - artifactory release
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
      EARTHLY_TOKEN: ${{ secrets.EARTHLY_TOKEN }}
    steps:
      - name: harden runner
        uses: step-security/harden-runner@1f99358870fe1c846a3ccba386cc2b2246836776 # v2.2.1
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: checkout
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0

      - name: update git branch
        run: |
          branch=""
          if [ -n "$GITHUB_HEAD_REF" ]; then
            branch="$GITHUB_HEAD_REF"
          else
            branch="${GITHUB_REF##*/}"
          fi
          git checkout -b "$branch" || true

      - name: setup qemu
        uses: docker/setup-qemu-action@e81a89b1732b9c48d79cd809d8d81d79c4647a18 # v2.1.0
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - name: setup earthly
        uses: earthly/actions-setup@cce953f2ea75f5ff76f6483a788bac66a733de3a # v1.0.5
        with:
          version: "latest"

      - name: docker login
        run: docker login  kickable.jfrog.io --username ${{ secrets.JFROG_USERNAME }}  --password "${{ secrets.JFROG_DOCKER_TOKEN }}"

      - name: set version
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: build and push docker app to artifactory
        run: earthly --ci --output --push +kickable --VERSION="$VERSION" --REPOSITORY="kickable.jfrog.io/kickable-docker-local/kickable"

      - name: build and push services to artifactory
        run: |
          earthly --ci --output --push +services --VERSION="$VERSION" --REPOSITORY="kickable.jfrog.io/kickable-docker-local/kickable"

      - name: build artifacts
        run: earthly --ci --output +archive --VERSION="${{ github.ref_name }}"

      - name: upload generic artifacts to artifactory
        uses: jfrog/setup-jfrog-cli@b767cc787302189426594d8036046e7dce4a30c4 # v3.2.0
        env:
          JF_URL: ${{ secrets.JF_URL }}
          JF_USER: ${{ secrets.JFROG_USERNAME }}
          JF_PASSWORD: ${{ secrets.JFROG_DOCKER_TOKEN }}
      - run: |
          jf rt u dist/kickable-rs_${{ github.ref_name }}_aarch64-apple-darwin.zip kickable-generic-local/kickable/${{ github.ref_name }}/kickable-rs_${{ github.ref_name }}_aarch64-apple-darwin.zip
          jf rt u dist/kickable-rs_${{ github.ref_name }}_aarch64-apple-darwin.zip.sha256 kickable-generic-local/kickable/${{ github.ref_name }}/kickable-rs_${{ github.ref_name }}_aarch64-apple-darwin.zip.sha256
          jf rt u dist/kickable-rs_${{ github.ref_name }}_aarch64-unknown-linux-musl.tar.gz kickable-generic-local/kickable/${{ github.ref_name }}/kickable-rs_${{ github.ref_name }}_aarch64-unknown-linux-musl.tar.gz
          jf rt u dist/kickable-rs_${{ github.ref_name }}_aarch64-unknown-linux-musl.tar.gz.sha256 kickable-generic-local/kickable/${{ github.ref_name }}/kickable-rs_${{ github.ref_name }}_aarch64-unknown-linux-musl.tar.gz.sha256
          jf rt u dist/kickable-rs_${{ github.ref_name }}_x86_64-apple-darwin.zip kickable-generic-local/kickable/${{ github.ref_name }}/kickable-rs_${{ github.ref_name }}_x86_64-apple-darwin.zip
          jf rt u dist/kickable-rs_${{ github.ref_name }}_x86_64-apple-darwin.zip.sha256 kickable-generic-local/kickable/${{ github.ref_name }}/kickable-rs_${{ github.ref_name }}_x86_64-apple-darwin.zip.sha256
          jf rt u dist/kickable-rs_${{ github.ref_name }}_x86_64-pc-windows-gnu.zip kickable-generic-local/kickable/${{ github.ref_name }}/kickable-rs_${{ github.ref_name }}_x86_64-pc-windows-gnu.zip
          jf rt u dist/kickable-rs_${{ github.ref_name }}_x86_64-pc-windows-gnu.zip.sha256 kickable-generic-local/kickable/${{ github.ref_name }}/kickable-rs_${{ github.ref_name }}_x86_64-pc-windows-gnu.zip.sha256
          jf rt u dist/kickable-rs_${{ github.ref_name }}_x86_64-unknown-linux-musl.tar.gz kickable-generic-local/kickable/${{ github.ref_name }}/kickable-rs_${{ github.ref_name }}_x86_64-unknown-linux-musl.tar.gz
          jf rt u dist/kickable-rs_${{ github.ref_name }}_x86_64-unknown-linux-musl.tar.gz.sha256 kickable-generic-local/kickable/${{ github.ref_name }}/kickable-rs_${{ github.ref_name }}_x86_64-unknown-linux-musl.tar.gz.sha256
