on:
  push:
    tags:
      - 'v*'

name: dockerhub release

permissions:
  contents: read

jobs:
  build:
    name: kickable - dockerhub release
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
      EARTHLY_TOKEN: ${{ secrets.EARTHLY_TOKEN }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          egress-policy: audit

      - name: checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: update git branch
        run: |
          branch=""
          if [ -n "$GITHUB_HEAD_REF" ]; then
            branch="$GITHUB_HEAD_REF"
          else
            branch="${GITHUB_REF##*/}"
          fi
          git checkout -b "$branch" || true

      - name: setup qemu
        uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 # v3.0.0
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - name: setup earthly
        uses: earthly/actions-setup@be3fe0c1f84e9776b5a184d21bf7a4a779ea2e6b # v1.0.8
        with:
          version: "latest"

#      - name: select satellite
#        run: earthly sat select hilo

      - name: docker login
        run: docker login --username kickable  --password "${{ secrets.DOCKER_HUB }}"

      - name: set version
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: build and push dockerhub app
        run: earthly --ci --output --push --use-inline-cache --save-inline-cache --max-remote-cache +kickable --VERSION="$VERSION" --REPOSITORY="kickable"

      - name: build dockerhub services
        run: |
          earthly --ci --output --push --use-inline-cache --save-inline-cache --max-remote-cache +services --VERSION="$VERSION" --REPOSITORY="kickable"