on:
  push:
    tags:
      - 'v*'

name: release

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
      EARTHLY_TOKEN: ${{ secrets.EARTHLY_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - name: update git branch
        run: |
          branch=""
          if [ -n "$GITHUB_HEAD_REF" ]; then
            branch="$GITHUB_HEAD_REF"
          else
            branch="${GITHUB_REF##*/}"
          fi
          git checkout -b "$branch" || true

      - name: setup ci
        run: sudo ./scripts/ci-setup.sh

      - name: select satellite
        run: earthly sat select neptune

      - name: run build
        run: earthly +archive --version='${{ github.ref_name }}'

      - name: run build
        run: ls -latr dist

      - name: create
        id: create
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_REPOSITORY: defstream/kickable-rs
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          body_path:  .changes/${{ github.ref_name }}.md
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: false
          generate_release_notes: true
          files: |
            dist/kickable-rs_${{ github.ref_name }}_aarch64-unknown-linux-musl.tar.gz
            dist/kickable-rs_${{ github.ref_name }}_aarch64-unknown-linux-musl.tar.gz.sha256
            dist/kickable-rs_${{ github.ref_name }}_x86_64-unknown-linux-musl.tar.gz
            dist/kickable-rs_${{ github.ref_name }}_x86_64-unknown-linux-musl.tar.gz.sha256
            dist/kickable-rs_${{ github.ref_name }}_aarch64-apple-darwin.zip
            dist/kickable-rs_${{ github.ref_name }}_aarch64-apple-darwin.zip.sha256
            dist/kickable-rs_${{ github.ref_name }}_x86_64-apple-darwin.zip
            dist/kickable-rs_${{ github.ref_name }}_x86_64-apple-darwin.zip.sha256
            dist/kickable-rs_${{ github.ref_name }}_x86_64-pc-windows-gnu.zip
            dist/kickable-rs_${{ github.ref_name }}_x86_64-pc-windows-gnu.zip.sha256


