on:
  push:
    branches:
      - artifactory
#    tags:
#      - 'v*'

name: artifactory release

jobs:
  build:
    name: kickable - artifactory release
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
      EARTHLY_TOKEN: ${{ secrets.EARTHLY_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - name: update git branch
        run: |
          branch=""
          if [ -n "$GITHUB_HEAD_REF" ]; then
            branch="$GITHUB_HEAD_REF"
          else
            branch="${GITHUB_REF##*/}"
          fi
          git checkout -b "$branch" || true

      - name: setup qemu
        uses: docker/setup-qemu-action@v2
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - name: setup ci
        run: sudo ./scripts/ci-setup.sh

      - name: select satellite
        run: earthly sat select titan

      - name: docker login
        run: docker login  kickable.jfrog.io --username ${{ secrets.JFROG_USERNAME }}  --password "${{ secrets.JFROG_DOCKER_TOKEN }}"

      - name: set version
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: build and push docker app to artifactory
        run: earthly --ci --output --push +kickable --VERSION="$VERSION" --REPOSITORY="kickable.jfrog.io/kickable-docker-local/kickable"

      - name: build services to artifactory
        run: |
          earthly --ci --output --push +services --VERSION="$VERSION" --REPOSITORY="kickable.jfrog.io/kickable-docker-local/kickable"


