on:
  push:
    tags:
      - 'v*'

name: ghcr.io release

jobs:
  build:
    name: kickable - ghcr.io release
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
      EARTHLY_TOKEN: ${{ secrets.EARTHLY_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - name: update git branch
        run: |
          branch=""
          if [ -n "$GITHUB_HEAD_REF" ]; then
            branch="$GITHUB_HEAD_REF"
          else
            branch="${GITHUB_REF##*/}"
          fi
          git checkout -b "$branch" || true

      - name: setup ci
        run: sudo ./scripts/ci-setup.sh

      - name: select satellite
        run: earthly sat select mars

      - name: docker login
        run: docker login ghcr.io --username ${{ github.repository_owner }}  --password "${{ secrets.GITHUB_TOKEN }}"

      - name: build and push docker app
        run: |
          earthly --push +kickable --version="${{ github.ref_name }}" --repository="ghcr.io/${{ github.repository }}"

      - name: build docker services
        run: |
          earthly --push +axum --version="${{ github.ref_name }}" --repository="ghcr.io/${{ github.repository }}"
          earthly --push +gotham --version="${{ github.ref_name }}" --repository="ghcr.io/${{ github.repository }}"
          earthly --push +graphul --version="${{ github.ref_name }}" --repository="ghcr.io/${{ github.repository }}"
          earthly --push +poem --version="${{ github.ref_name }}" --repository="ghcr.io/${{ github.repository }}"
          earthly --push +rocket --version="${{ github.ref_name }}" --repository="ghcr.io/${{ github.repository }}"
          earthly --push +rouille --version="${{ github.ref_name }}" --repository="ghcr.io/${{ github.repository }}"
          earthly --push +salvo --version="${{ github.ref_name }}" --repository="ghcr.io/${{ github.repository }}"
          earthly --push +tonic-client --version="${{ github.ref_name }}" --repository="ghcr.io/${{ github.repository }}"
          earthly --push +tonic-server --version="${{ github.ref_name }}" --repository="ghcr.io/${{ github.repository }}"
          earthly --push +trillium --version="${{ github.ref_name }}" --repository="ghcr.io/${{ github.repository }}"
          earthly --push +viz --version="${{ github.ref_name }}" --repository="ghcr.io/${{ github.repository }}"
          earthly --push +warp --version="${{ github.ref_name }}" --repository="ghcr.io/${{ github.repository }}"
