# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# A sample workflow which checks out the code, builds a container
# image using Docker and scans that image for vulnerabilities using
# Snyk. The results are then uploaded to GitHub Security Code Scanning
#
# For more examples, including how to limit scans to only high-severity
# issues, monitor images for newly disclosed vulnerabilities in Snyk and
# fail PR checks for new vulnerabilities, see https://github.com/snyk/actions/

name: snyk - container

on:
  push:
    branches: [ "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]
  schedule:
    - cron: '18 13 * * 2'

permissions:
  contents: read

jobs:
  container:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    runs-on: ubuntu-latest
    steps:
      - name: harden runner
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.depot.dev:443
            auth.docker.io:443
            dl.depot.dev:443
            github.com:443
            index.docker.io:443
            objects.githubusercontent.com:443
            registry-1.docker.io:443
            undefined:443

      - name: checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: setup depot
        uses: depot/setup-action@0cd1716c2eb8606eee7f18de8f87fddd0e1c2fd2 # v1.4.2

      - name: build docker
        run: depot build --load --platform linux/amd64,linux/arm64 -f docker/Dockerfile.builder -t container .
        env:
          DEPOT_TOKEN: ${{ secrets.DEPOT_TOKEN }}

      - name: snyk - builder
        continue-on-error: true
        uses: snyk/actions/docker@3e2680e8df93a24b52d119b1305fb7cedc60ceae
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          sarif: true
          image: container
          args: --file=docker/Dockerfile

      - name: snyk - builder - upload
        uses: github/codeql-action/upload-sarif@74483a38d39275f33fcff5f35b679b5ca4a26a99 # v2.22.5
        with:
          sarif_file: snyk.sarif